version: '3.1'

services:
  postgres-db-zio-reactive:
    container_name: postgres-db-zio-reactive
    image: postgres
    restart: always
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      - "POSTGRES_USER=ziotapir"
      - "POSTGRES_PASSWORD=ziotapir"
    ports:
      - "5100:5432"

  zookeeper-zio-reactive:
    container_name: zookeeper-zio-reactive
    image: confluentinc/cp-zookeeper:7.7.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - reactive-zio-network

  kafka-zio-reactive:
    container_name: kafka-zio-reactive
    image: confluentinc/cp-kafka:7.7.1
    depends_on:
      - zookeeper-zio-reactive
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-zio-reactive:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - reactive-zio-network

  kafka-ui-reactive:
    container_name: kafka-ui-zio-reactive
    image: provectuslabs/kafka-ui:v0.7.2
    depends_on:
      - kafka-zio-reactive
    ports:
      - "9099:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: host.docker.internal:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-zio-reactive:2181
    networks:
      - reactive-zio-network

networks:
  reactive-zio-network:
    driver: bridge