version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: ziotapir-postgres-db
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      - "POSTGRES_USER=ziotapir"
      - "POSTGRES_PASSWORD=ziotapir"
    ports:
      - "5100:5432"