CREATE TABLE IF NOT EXISTS products (
    id BIGSERIAL PRIMARY KEY,
    asin VARCHAR(255) UNIQUE NOT NULL,
    name TEXT UNIQUE NOT NULL,
    url TEXT NOT NULL,
    images TEXT[],
    created TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated TIMESTAMPTZ NOT NULL DEFAULT now()
);